#!/bin/sh

echo "Cleaning in progress. Please wait..."

# Remove `.git` directory
rm -rf .git/        && \
# Remove the `.sass-cache` directory
rm -rf .sass-cache/ && \
# Remove the framework readme
rm -rf README.md    && \
# Initialize a new Git instance
git init            && \
# Remove the clean file
#rm clean
# Add all current files
git add --all       && \

# htaccess
if [ -e .htaccess ]; then
	read -p "Do you need the htaccess file? " -n 1 -r
	if [[ $REPLY =~ ^[Nn]$ ]]; then
		# Remove `.htaccess`
		rm .htaccess
	fi
fi

printf "\n"

# Sublime Text SFTP
if [ -e sftp-config.json ]; then
	read -p "Do you need the Sublime Text SFTP config? " -n 1 -r
	if [[ $REPLY =~ ^[Nn]$ ]]; then
		# Remove `sftp-config.json`
		rm sftp-config.json
	fi
fi

printf "\n"

# Sublime Text Project
if [ -e *.sublime-project ]; then
	read -p "Do you need the Sublime Text Project config? " -n 1 -r
	if [[ $REPLY =~ ^[Nn]$ ]]; then
		# Remove `*.sublime-project` and `*.sublime-workspace`
		rm *.sublime-project
		if [ -e *.sublime-workspace ]; then
			rm *.sublime-workspace
		fi
	fi
fi

printf "\n"

# Check for a commit
read -p "Do you want to do an initial commit? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
	# Initial commit
	git commit -am "Initial commit"
fi

printf "\n"

echo "Framework successfully installed!"

git status